name: PM2.5 Fetcher

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:    # manual trigger option

jobs:
  run-fetcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade scikit-learn

      - name: Run PM2.5 fetcher
        env:
          VISUAL_CROSSING_KEY: ${{ secrets.VISUAL_CROSSING_KEY }}
          WAQI_TOKEN: ${{ secrets.WAQI_TOKEN }}
        run: |
          python pm25_fetcher.py
